# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/serranodsdd/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/serranodsdd/proprietary/lib/libsec-ril-dsds.so:system/lib/libsec-ril-dsds.so \
    vendor/samsung/serranodsdd/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/serranodsdd/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/serranodsdd/proprietary/lib/libbtnv.so:system/lib/libbtnv.so \
    vendor/samsung/serranodsdd/proprietary/bin/fm_qsoc_patches:system/bin/fm_qsoc_patches \
    vendor/samsung/serranodsdd/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/serranodsdd/proprietary/bin/thermald:system/bin/thermald \
    vendor/samsung/serranodsdd/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/samsung/serranodsdd/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/samsung/serranodsdd/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/serranodsdd/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/serranodsdd/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/samsung/serranodsdd/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/egl/libplayback_adreno.so:system/vendor/lib/egl/libplayback_adreno.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/serranodsdd/proprietary/lib/libI420colorconvert.so:system/lib/libI420colorconvert.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/samsung/serranodsdd/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/serranodsdd/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/serranodsdd/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/serranodsdd/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/serranodsdd/proprietary/lib/libcordon.so:system/lib/libcordon.so \
    vendor/samsung/serranodsdd/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/serranodsdd/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/serranodsdd/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/serranodsdd/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/serranodsdd/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/serranodsdd/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/serranodsdd/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/serranodsdd/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/serranodsdd/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/samsung/serranodsdd/proprietary/bin/irsc_util:system/bin/irsc_util \
    vendor/samsung/serranodsdd/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/samsung/serranodsdd/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/serranodsdd/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/serranodsdd/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/serranodsdd/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
    vendor/samsung/serranodsdd/proprietary/lib/libadsprpc.so:system/lib/libadsprpc.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_imx175_antishake.so:system/lib/libchromatix_imx175_antishake.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_imx175_default_video.so:system/lib/libchromatix_imx175_default_video.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_imx175_lls.so:system/lib/libchromatix_imx175_lls.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_imx175_preview.so:system/lib/libchromatix_imx175_preview.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_imx175_zsl.so:system/lib/libchromatix_imx175_zsl.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_imx175_zsl_drama.so:system/lib/libchromatix_imx175_zsl_drama.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_imx175_zsl_panorama.so:system/lib/libchromatix_imx175_zsl_panorama.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k3h5xa_antishake.so:system/lib/libchromatix_s5k3h5xa_antishake.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k3h5xa_default_video.so:system/lib/libchromatix_s5k3h5xa_default_video.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k3h5xa_lls.so:system/lib/libchromatix_s5k3h5xa_lls.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k3h5xa_preview.so:system/lib/libchromatix_s5k3h5xa_preview.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k3h5xa_zsl.so:system/lib/libchromatix_s5k3h5xa_zsl.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k3h5xa_zsl_drama.so:system/lib/libchromatix_s5k3h5xa_zsl_drama.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k3h5xa_zsl_panorama.so:system/lib/libchromatix_s5k3h5xa_zsl_panorama.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k6a3yx_default_video.so:system/lib/libchromatix_s5k6a3yx_default_video.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k6a3yx_preview.so:system/lib/libchromatix_s5k6a3yx_preview.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k6a3yx_smart_stay.so:system/lib/libchromatix_s5k6a3yx_smart_stay.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k6a3yx_vt.so:system/lib/libchromatix_s5k6a3yx_vt.so \
    vendor/samsung/serranodsdd/proprietary/lib/libchromatix_s5k6a3yx_vt_hd.so:system/lib/libchromatix_s5k6a3yx_vt_hd.so \
    vendor/samsung/serranodsdd/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/serranodsdd/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/serranodsdd/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/serranodsdd/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmercury.so:system/lib/libmercury.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/samsung/serranodsdd/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/serranodsdd/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/serranodsdd/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/samsung/serranodsdd/proprietary/lib/libTsAccm.so:system/lib/libTsAccm.so \
    vendor/samsung/serranodsdd/proprietary/lib/libTsAwb.so:system/lib/libTsAwb.so \
    vendor/samsung/serranodsdd/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/serranodsdd/proprietary/bin/insthk:system/bin/insthk \
    vendor/samsung/serranodsdd/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/samsung/serranodsdd/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/samsung/serranodsdd/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/samsung/serranodsdd/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/serranodsdd/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/serranodsdd/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/serranodsdd/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/samsung/serranodsdd/proprietary/lib/libOmxAmrwbplusDec.so:system/lib/libOmxAmrwbplusDec.so \
    vendor/samsung/serranodsdd/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/samsung/serranodsdd/proprietary/lib/libOmxMux.so:system/lib/libOmxMux.so \
    vendor/samsung/serranodsdd/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/samsung/serranodsdd/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/samsung/serranodsdd/proprietary/vendor/firmware/bcm2079xB4_firmware.ncd:system/vendor/firmware/bcm2079xB4_firmware.ncd \
    vendor/samsung/serranodsdd/proprietary/vendor/firmware/bcm2079xB4_pre_firmware.ncd:system/vendor/firmware/bcm2079xB4_pre_firmware.ncd
